project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import rfeed.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include(rfeed.urls)),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rfeed/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.core.urlresolvers import reverse_lazy
from rfeed.views import ViewPrincipal, ViewGerenciarPedidos, ViewGerenciarIngredientes

urlpatterns = patterns('',
    url(r'^$', ViewPrincipal.as_view(), name='principal'),
    url(r'^pedidos$', ViewGerenciarPedidos.as_view(), name='pedidos'),
    url(r'^ingredientes$', ViewGerenciarIngredientes.as_view(), name='ingredientes'),

    url(r'^login$', login, {'template_name': 'rfeed/login.html'}, name='login'),
    url(r'^logout$', logout, {'next_page': reverse_lazy('principal')}, name='logout'),
)

rfeed/models/balanca.py
from django.db import models
from decimal import Decimal as D

class Balanca(models.Model):
    class Meta:
        app_label = 'rfeed'
        db_table = 'balanca'

    ref = models.CharField("referencia da balanca", max_length=3)
    peso_atual = models.DecimalField("peso atual da balanca", max_digits=6, decimal_places=3, default=D('0.0'))

    def __unicode__(self):
        return u'#{}'.format(self.ref)

rfeed/models/ingrediente.py
# coding: utf-8
from django.db import models
from rfeed.models import Balanca


class Ingrediente(models.Model):
    class Meta:
        app_label = 'rfeed'
        db_table = 'ingrediente'

    nome = models.CharField("ingrediente", max_length=100)
    balanca = models.OneToOneField(Balanca, verbose_name=u'balança')

    def __unicode__(self):
        return u'{}'.format(self.nome)

rfeed/models/item.py
from django.db import models
from rfeed.models import Ingrediente


class Item(models.Model):
    class Meta:
        app_label = 'rfeed'
        db_table = 'item'

    nome = models.CharField("nome do item", max_length=100)
    ingredientes = models.ManyToManyField(Ingrediente, through='IngredientesPorItem')

    def __unicode__(self):
        return u'{}'.format(self.nome)


class IngredientesPorItem(models.Model):
    class Meta:
        app_label = 'rfeed'
        db_table = 'ingredientes_por_item'

    UNIDADE_CHOICES = (
        ('Kg', 'Kilogramas'),
        ('g', 'Gramas'),
        ('L', 'Litros'),
        ('mL', 'Mililitros'),
        ('un', 'Unidades')
    )

    item = models.ForeignKey(Item)
    ingrediente = models.ForeignKey(Ingrediente)
    quantidade = models.DecimalField("quantidade", max_digits=6, decimal_places=3)
    unidade = models.CharField("unidade", max_length=2, choices=UNIDADE_CHOICES, default='un')

    def __unicode__(self):
        return u'<IngredientesPorItem item {} ingrediente {} quantidade {}>'.format(
            self.item.nome, self.ingrediente.nome, self.quantidade)

rfeed/models/mesa.py
from django.db import models


class Mesa(models.Model):
    class Meta:
        app_label = 'rfeed'
        db_table = 'mesa'

    codigo = models.CharField("referencia da mesa", max_length=3)

    def __unicode__(self):
        return u'{}'.format(self.codigo)

rfeed/models/pedido.py
from django.db import models
from rfeed.models import Item, Mesa


class Pedido(models.Model):
    class Meta:
        app_label = 'rfeed'
        db_table = 'pedido'

    STATUS_CHOICES = (
        ('Aberto', 'Aberto'),
        ('Fechado', 'Fechado'),
        ('Cancelado', 'Cancelado')
    )

    mesa = models.ForeignKey(Mesa)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='Aberto')
    data_hora = models.DateTimeField("hora/data do pedido", auto_now_add=True)
    itens = models.ManyToManyField(Item, through='ItensPorPedido')

    def __unicode__(self):
        return u'<Pedido: id {} status {} data {} mesa {} num_items {}>'.format(
            self.pk, self.status, self.data_hora, self.mesa.codigo, self.itens.count())


class ItensPorPedido(models.Model):
    class Meta:
        app_label = 'rfeed'
        db_table = 'itens_por_pedido'

    pedido = models.ForeignKey(Pedido)
    item = models.ForeignKey(Item)
    quantidade = models.PositiveSmallIntegerField("quantidade", default=1)

    def __unicode__(self):
        return u'{} {}'.format(self.quantidade, self.item)

rfeed/forms/ingrediente.py
# coding: utf-8
from django import forms
from django.db.models import Q
from rfeed.models import Ingrediente, Balanca


class IngredienteForm(forms.ModelForm):
    def __init__(self, instance=None, *args, **kwargs):
        super(IngredienteForm, self).__init__(instance=instance, *args, **kwargs)

        if instance:
            self.fields['balanca'].queryset = Balanca.objects.filter(
                 Q(ingrediente=None) | Q(pk=instance.balanca.pk))
            self.fields['balanca'].initial = instance.balanca.pk
        else:
            self.fields['balanca'].queryset = Balanca.objects.filter(ingrediente=None)


    class Meta:
        model = Ingrediente

rfeed/forms/pedido.py
#encoding: utf-8
from django import forms
from rfeed.models import Pedido, ItensPorPedido


class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        exclude = ('itens',)


class ItensPorPedidoForm(forms.ModelForm):
    class Meta:
        model = ItensPorPedido

    def __init__(self, instance=None, *args, **kwargs):
        super(ItensPorPedidoForm, self).__init__(instance=instance, *args, **kwargs)

        if instance:
            return
        else:
            self.fields['quantidade'].initial = 1

    def clean_quantidade(self):
        qt = self.cleaned_data['quantidade']

        if qt > 0:
            return qt
        else:
            raise forms.ValidationError('Certifique-se que a quantidade é maior que 1.')

rfeed/controllers/ingredientes.py
# coding: utf-8
from rfeed.models import Ingrediente
from rfeed.forms import IngredienteForm


class ControladorGerenciarIngredientes(object):
    """"""

    def buscar_ingrediente(self, pk):
        return Ingrediente.objects.get(pk=pk)


    def buscar_ingredientes(self):
        return list(Ingrediente.objects.all())


    def buscar_formulario_ingrediente(self, data=None, pk=None):
        if not pk:
            return IngredienteForm(data=data)

        ingrediente = self.buscar_ingrediente(pk)
        return IngredienteForm(data=data, instance=ingrediente)


    def validar_formulario_ingrediente(self, data, pk=None):
        form = self.buscar_formulario_ingrediente(data, pk)

        if form.is_valid():
            return True, form, None
        else:
            return False, form, form.errors


    def cadastrar_ingrediente(self, nome, balanca):
        return Ingrediente.objects.create(nome=nome, balanca=balanca)


    def atualizar_ingrediente(self, pk, nome, balanca):
        ingrediente = Ingrediente.objects.get(pk=pk)
        ingrediente.nome = nome
        ingrediente.balanca = balanca
        ingrediente.save()
        return ingrediente


    def remover_ingrediente(self, pk):
        try:
            tmp = Ingrediente.objects.get(pk=pk)
            tmp.delete()
            return True
        except:
            return False


    



    

rfeed/controllers/pedidos.py
# coding: utf-8
from django.http import QueryDict
from rfeed.models import Pedido, ItensPorPedido
from rfeed.forms import PedidoForm, ItensPorPedidoForm


class ControladorGerenciarPedidos(object):
    """"""

    def buscar_pedido(self, pk):
        return Pedido.objects.get(pk=pk)


    def buscar_pedidos(self):
        return list(Pedido.objects.all())


    def buscar_formulario_pedido(self, data, pk):
        if not pk:
            return PedidoForm(data=data)

        pedido = self.buscar_pedido(pk)
        return PedidoForm(data=data, instance=pedido)


    def validar_formulario_pedido(self, data, pk=None):
        form = self.buscar_formulario_pedido(data=data, pk=pk)
        
        if form.is_valid():
            return True, form, None
        else:
            return False, form, form.errors


    def buscar_formulario_item(self, data=None):
        return ItensPorPedidoForm(data=data)


    def cadastrar_pedido(self, mesa, status):
        return Pedido.objects.create(mesa=mesa, status=status)


    def validar_formularios_itens(self, pedido, data):
        querydicts = [QueryDict('pedido={}&item={}&quantidade={}'.format(pedido, item, quantidade))
                            for item, quantidade in
                            zip(data.getlist(u'item'), data.getlist(u'quantidade'))]

        forms = map(lambda qs: self.buscar_formulario_item(data=qs), querydicts)

        is_valid = all(map(lambda form: form.is_valid(), forms))
        if is_valid:
            return True, forms, None
        else:
            return False, None, {'itens': [f.errors for f in forms]}


    def cadastrar_item(self, pedido, item, quantidade):
        return ItensPorPedido.objects.create(pedido=pedido, item=item, quantidade=quantidade)


    def atualizar_status_pedido(self, pk, status):
        try:
            pedido = self.buscar_pedido(pk)
            pedido.status = status
            pedido.save()
            return True
        except:
            return False


    def remover_pedido(self, pk):
        try:
            tmp = Pedido.objects.get(pk=pk)
            tmp.delete()
            return True
        except:
            return False

rfeed/controllers/principal.py
# coding: utf-8

rfeed/views/ingredientes.py
# coding: utf-8
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, QueryDict
from rfeed.models import Ingrediente
from rfeed.forms import IngredienteForm
from rfeed.decorators import group_required
from urlparse import parse_qs
import json
from rfeed import Fachada


class ViewGerenciarIngredientes(TemplateView):
    """View que gerencia a adição/remoção/modificação de ingredientes."""

    template_name = 'rfeed/ingredientes.html'
    fachada = Fachada.get_instance()


    @method_decorator(csrf_exempt)
    @method_decorator(group_required('Administrador'))
    def dispatch(self, *args, **kwargs):
        """Despacha a requisição para o método correto: get, post, put ou delete."""
        return super(ViewGerenciarIngredientes, self).dispatch(*args, **kwargs)


    def get_context_data(self, **kwargs):
        """Gera as variáveis para o template da página."""
        context = super(ViewGerenciarIngredientes, self).get_context_data(**kwargs)
        context['ingredientes'] = self.fachada.buscar_ingredientes()

        return context


    def renderizar_formulario_ingrediente(self, request, pk):
        form, value = self.fachada.buscar_formulario_editavel_ingrediente(pk)

        return render_to_response('rfeed/form_ingrediente.html', {'form': form, 'value': value},
            context_instance=RequestContext(request))


    def get(self, request, *args, **kwargs):
        # Pegar formulário para ingrediente
        if request.is_ajax():
            pk = request.GET.get('pk', None)
            return self.renderizar_formulario_ingrediente(request, pk)

        # GET normal
        return super(ViewGerenciarIngredientes, self).get(request, *args, **kwargs)


    def post(self, request):
        valid, errors = self.fachada.cadastrar_ingrediente(request.POST)

        if valid:
            return HttpResponse(json.dumps({'success': True}), content_type='application/json')

        return HttpResponse(json.dumps({'success': False, 'errors': errors}),
            content_type='application/json')


    def put(self, request):
        data = QueryDict(request.body)
        pk = int(data['pk'][0])

        valid, errors = self.fachada.atualizar_ingrediente(data, pk)

        if valid:
            return HttpResponse(json.dumps({'success': True}), content_type='application/json')

        return HttpResponse(json.dumps({'success': False, 'errors': errors}),
            content_type='application/json')


    def delete(self, request):
        data = json.loads(request.body)
        pk = int(data['pk'])
        result = self.fachada.remover_ingrediente(pk)

        return HttpResponse(json.dumps({'success': result}), content_type='application/json')

rfeed/views/pedidos.py
#coding: utf-8
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, QueryDict
from rfeed.models import Item, Pedido, ItensPorPedido
from rfeed.decorators import group_required
from urlparse import parse_qs
import json
from rfeed import Fachada


class ViewGerenciarPedidos(TemplateView):
    """View que gerencia a adição/remoção/modificação de pedidos."""

    template_name = 'rfeed/pedidos.html'
    fachada = Fachada.get_instance()

    @method_decorator(csrf_exempt)
    @method_decorator(group_required('Administrador', 'Supervisor'))
    def dispatch(self, *args, **kwargs):
        """Despacha a requisição para o método correto: get, post, put ou delete."""
        return super(ViewGerenciarPedidos, self).dispatch(*args, **kwargs)


    def get_context_data(self, **kwargs):
        """Gera as variáveis para o template da página."""
        context = super(ViewGerenciarPedidos, self).get_context_data(**kwargs)
        context['pedidos'] = self.fachada.buscar_pedidos()

        return context


    def renderizar_formulario_pedido(self, request, pk):
        form = self.fachada.buscar_formulario_editavel_pedido(pk)

        return render_to_response('rfeed/form_pedido.html', {'form': form},
            context_instance=RequestContext(request))


    def renderizar_formulario_item(self, request):
        form, number = self.fachada.buscar_formulario_editavel_item()

        return render_to_response('rfeed/form_pedido_item.html', {'form': form, 'number': number},
            context_instance=RequestContext(request))


    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            if 'item' in request.GET:
                return self.renderizar_formulario_item(request)

            pk = request.GET.get('pk', None)
            return self.renderizar_formulario_pedido(request, pk)

        # GET normal
        return super(ViewGerenciarPedidos, self).get(request, *args, **kwargs)


    def post(self, request):
        valid, errors = self.fachada.cadastrar_pedido(request.POST)

        if valid:
            return HttpResponse(json.dumps({'success': True}), content_type='application/json')

        return HttpResponse(json.dumps({'success': False, 'errors': errors}),
            content_type='application/json')


    def delete(self, request):
        data = json.loads(request.body)
        pk = int(data['pk'])
        result = self.fachada.remover_pedido(pk)

        return HttpResponse(json.dumps({'success': result}), content_type='application/json')


    def put(self, request):
        data = QueryDict(request.body)
        pk = int(data['pk'])

        if 'only_status' in data:
            status = data['status']
            result = self.fachada.atualizar_status_pedido(pk, status)
            return HttpResponse(json.dumps({'success': result}), content_type='application/json')

        return HttpResponse(json.dumps({'success': False}), content_type='application/json')

__n = 0
def get_number():
    global __n
    __n += 1
    return __n

def reset_number():
    global __n
    __n = 0

rfeed/views/principal.py
from django.views.generic import TemplateView


class ViewPrincipal(TemplateView):
    template_name = 'rfeed/principal.html'

rfeed/templates/rfeed/base.html
{% load staticfiles %}
{% load selectable_anchor %}
<!DOCTYPE html>
    <html lang="en">
        <head>
        <meta charset="utf-8">
        <title>{% block title %}RFeed{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Le styles -->
        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
        <style>
            body {
                padding-top: 60px;
            }
        </style>
        <link href="{% static "css/bootstrap-responsive.css" %}" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="../assets/js/html5shiv.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top active">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="{% url principal %}">RFeed</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            {% selectable_anchor "pedidos" Pedidos %}
                            {% selectable_anchor "ingredientes" Ingredientes %}
                        </ul>
                    </div>

                    {% if not login_page %}
                    <div class="pull-right">
                        <ul class="nav">
                            {% if user.is_authenticated %}
                            <li><p class="navbar-text">{{ user.username }}</p></li>
                            {% else %}
                            <li><p class="navbar-text">Você não está logado</p></li>
                            {% endif %}
                        </ul>
                        {% if user.is_authenticated %}
                        <a class="btn btn-danger" href="{% url logout %}">Logout</a>
                        {% else %}
                        <a class="btn btn-success" href="{% url login %}">Login</a>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div> <!-- /container -->

        <script src="{% static "js/jquery.js" %}"></script>
        <script src="{% static "js/bootstrap.js" %}"></script>

        {% block javascript %}{% endblock %}
    </body>
</html>

rfeed/templates/rfeed/form_ingrediente.html
<form id="modal_form" class="form-horizontal" method="post" action="{% url ingredientes %}">
    {% csrf_token %}
    <div class="control-group">
        <label class="control-label" for="id_nome">Nome do ingrediente</label>
        <div class="controls">
            <input type="text" id="id_nome" name="nome" placeholder="Ingrediente" maxlength="100" 
            {% if value %} value="{{ value }}"{% endif %}>
        </div>
    </div>
    <div id="error_ingrediente" class="modal_errors"></div>
    <div class="control-group">
        <label class="control-label" for="id_balanca">Balança</label>
        <div class="controls">
            {{ form.balanca }}
        </div>
    </div>
    <div id="error_balanca" class="modal_errors"></div>

    <!-- <div class="control-group">
        <label class="control-label" for="id_teste">Teste</label>
        <div class="controls">
            <input type="text" id="id_teste" name="teste"  maxlength="100">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="id_teste2">Teste</label>
        <div class="controls">
            <input type="text" id="id_teste2" name="teste"  maxlength="100">
        </div>
    </div> -->
</form>

rfeed/templates/rfeed/form_pedido.html
<form id="modal_form" class="form-horizontal" method="post" action="{% url pedidos %}">
    {% csrf_token %}
    <div class="control-group">
        <label class="control-label" for="id_mesa">Mesa</label>
        <div class="controls">
            {{ form.mesa }}
        </div>
    </div>
    <div id="error_mesa" class="modal_errors"></div>
    
    <div class="control-group">
        <label class="control-label" for="id_status">Status</label>
        <div class="controls">
            {{ form.status }}
        </div>
    </div>
    <div id="error_status" class="modal_errors"></div>
    
    <div class="control-group">
        <label class="control-label" for="id_itens">Itens</label>
        <div class="controls">
            <a id="button_add_item" class="btn btn-success" href="#">Adicionar</a>
        </div>
    </div>

    <div id="form_itens"></div>  
</form>

rfeed/templates/rfeed/form_pedido_item.html
<div class="control-group" id="form_item_{{ number }}">
    <div class="controls form-inline">
        <input class="input-mini" type="text" id="id_quantidade_{{ number }}" name="quantidade" placeholder="Qtde."  maxlength="100" {% if form.quantidade.value %}value="{{ form.quantidade.value }}{% endif %}">
        {{ form.item }}
        <a class="button_rm_item btn btn-small btn-danger" href="#">Remover</a>
    </div>
</div>
<div id="error_item" class="modal_errors"></div>

rfeed/templates/rfeed/ingredientes.html
{% extends "rfeed/base.html" %}
{% load staticfiles %}

{% block content %}
<br />
<div class="row">
    <div class="span4 offset4" style="text-align: center">
        <h2>Gerenciar ingredientes</h2>
    </div>
</div>
<br />
<div class="row">
    <div class="span4 offset4" style="text-align: center">
        <a id="button_add_ingrediente" class="btn btn-success btn-large btn-block">Adicionar ingrediente</a>
    </div>
</div>
<br />
<div class="row">
    <div class="span10 offset1">
        <table class="table table-hover table-bordered">
            <thead>
                <tr style="background-color: #d9edf7;">
                    <td style="display: none;"></td>
                    <td><strong>Nome do ingrediente</strong></td>
                    <td><strong>Balança</strong></td>
                    <td><strong>Remover</strong></td>
                </tr>
            </thead>
            <tbody>
                {% for ingrediente in ingredientes %}
                <tr>
                    <td style="display: none;" class="pk">{{  ingrediente.pk }}</td>
                    <td class="edit">{{ ingrediente.nome }}</td>
                    <td class="edit">{{ ingrediente.balanca }}</td>
                    <td>
                        <a class="button_rm_ingrediente btn btn-danger btn-mini btn-block" href="#">Remover</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br />
</div>

<!-- Janela de adicionar ingrediente -->
<div id="modal_container" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="modal_label">Adicionar ingrediente</h3>
    </div>
    <div id="modal_form_container" class="modal-body"></div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <button id="button_modal_confirm" class="btn btn-primary">Adicionar</button>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static "js/gerenciar_ingredientes.js" %}"></script>

<script type="text/javascript">
    $(window).load(function () {
        pagina = new rfeed.GerenciarIngredientes("{% url ingredientes %}");
    });
</script>
{% endblock %}

rfeed/templates/rfeed/login.html
{% extends "rfeed/base.html" %}

{% block content %}
<div class="row">
    <div class="span12">
        {% if form.errors %}
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Atenção!</strong> {{ form.non_field_errors.0 }}
        </div>
        {% endif %}

        <form class="form-horizontal" method="post" action="{% url login %}">
            {% csrf_token %}
            <div class="control-group">
                <label class="control-label" for="id_username">Usuário</label>
                <div class="controls">
                    <input type="text" id="id_username" name="username" placeholder="Usuário" maxlength="30">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_password">Password</label>
                <div class="controls">
                    <input type="password" id="id_password" name="password" placeholder="Senha">
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-success">Efetuar login</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}{% endblock %}

rfeed/templates/rfeed/pedidos.html
{% extends "rfeed/base.html" %}
{% load staticfiles %}

{% block content %}
<br />

<div class="row">
    <div class="span4 offset4" style="text-align: center">
        <h2>Gerenciar pedidos</h2>
    </div>
</div>

<br />

<div class="row">
    <div class="span4 offset4" style="text-align: center">
        <a id="button_add_pedido" class="btn btn-success btn-large btn-block">Adicionar pedido</a>
    </div>
</div>

<br />

<div class="row">
    <div class="span10 offset1">
        <table class="table table-hover table-bordered">
            <thead>
                <tr style="background-color: #d9edf7;">
                    <td><strong># Pedido</strong></td>
                    <td><strong>Mesa</strong></td>
                    <td><strong>Itens</strong></td>
                    <td><strong>Hora</strong></td>
                    <td><strong>Status</strong></td>
                    <td><strong>Remover</strong></td>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                <tr>
                    <td class="edit">#<span class="pk">{{ pedido.pk }}</span></td>
                    <td class="edit">{{ pedido.mesa }}</td>
                    <td class="edit">
                        <table class="table table-striped table-condensed">
                            <tbody>
                                {% for item in pedido.itensporpedido_set.all %}
                                <tr><td>
                                    {{ item }}
                                </td></tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    <td class="edit">{{ pedido.data_hora }}</td>
                    <td>{{ pedido.status_selector }}</td>
                    <td>
                        <a class="button_rm_pedido btn btn-danger btn-mini btn-block" href="#">Remover</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br />
</div>

<!-- Janela de adicionar pedido -->
<div id="modal_container" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="modal_label">Adicionar pedido</h3>
    </div>
    <div id="modal_form_container" class="modal-body"></div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <button id="button_modal_confirm" class="btn btn-primary">Adicionar</button>
    </div>
</div>

<div class="row">
    <div class="span10 offset1">
        <div id="errors"></div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static "js/gerenciar_pedidos.js" %}"></script>

<script type="text/javascript">
    $(window).load(function () {
        pagina = new rfeed.GerenciarPedidos("{% url pedidos %}");
    });
</script>
{% endblock %}

rfeed/templates/rfeed/principal.html
{% extends "rfeed/base.html" %}
{% block content %}
<h1>Bem vindo ao RFeed</h1>
<br /><br />
<div class="row">
    {% if user.is_authenticated %}
    <div class="span10 offset1">
        <table class="table">
            <thead>
                <tr>
                    <th>Usuário</th>
                    <th>Função</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ user.username }}</td>
                    <td>
                        {% if user.groups.exists %}
                        {{ user.groups.all.0 }}
                        {% else %}
                        Funcionário
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="span4 offset4">
        <h5>Você precisa fazer o login para ter acesso ao sistema</h5>
        <a class="btn btn-success btn-large btn-block" href="{% url login %}">Login</a>
    </div>
    {% endif %}
</div>
{% endblock %}

rfeed/templates/rfeed/teste.html
<p>teste</p>
<p>{{ value }} -- asd</p>